ktor:
  application:
    modules:
      - com.arnav.ApplicationKt.module
  deployment:
    port: 8080
  database:
    jdbcUrl: "jdbc:postgresql:cluster_db"
    jdbcDriver: "org.postgresql.Driver"
    user: "admin"
    password: ${DATABASE_PASSWORD}